all:
        gfortran -c object.f95
        gfortran -c verlet_integrator.f95
        gfortran -c runge_kutta.f95
        gfortran -c inputFileReader.f95
        gfortran -c main.f95
        gfortran -o run_verlet.out main.o object.o verlet_integrator.o inputFileReader.o
